### ISSUE TITLE
jupyter-base-notebook mising Git

### ISSUE THREAD

**Issue by eeholmes** [nmfs-opensci/container-images#2]
error

git command not found - please ensure you have Git > 2 installed

**Comment by timhaverland-noaa** [comment]
When I try to install git via conda my docker build on my local runs fine, but the jupyter labextension install @jupyter-widgets/jupyterlab-manager@2 fails in the github action docker build. I *think* this is due an out of memory issue on the github runner. I'm going to change the order of the install to see if I can preserve memory for the jupyter build step.

**Comment by timhaverland-noaa** [comment]
Moving the git install toward the end of the build allowed the build to complete, but in the git install openssl was upgraded to 3.x, which causes any future jupyter lab build to fail. I will need to find a way of installing git and keeping openssl at 1.x.

**Comment by timhaverland-noaa** [comment]
Specifically installed git 2.30.2 and that seems to have resolved jupyter lab build issues.

**Comment by eeholmes-uw** [comment]
@timhaverland-noaa 

Try?

```
RUN apt-get update -qq && apt-get -y install git
```

That is how I would normally install git (and ilk). Doing it this way will not use conda so will not downgrade any modules.

**Comment by eeholmes** [comment]
Also there might be other things that would be useful. Here is a apt.txt file for another Dockerfile

apt.txt
```
zsh
curl
git
jq
htop
tmux
tree
vim
neovim
emacs
net-tools
iproute2
xclip
ffmpeg
build-essential
software-properties-common

libgl1-mesa-glx
dbus-x11
xorg
xfce4
xfce4-panel
xfce4-session
xfce4-settings
xubuntu-icon-theme
```

Install with something like. 
```
RUN apt-get update --fix-missing > /dev/null \
        # Read apt.txt line by line, and execute apt-get install -y for each line in apt.txt
        && xargs -a apt.txt apt-get install -y \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/* 
```

I modified these lines from the pangeo docker-stacks Dockerfile. I have not tested.
https://github.com/pangeo-data/pangeo-docker-images/blob/45572b778e82faf0661c622d65e21fcb2538084a/base-image/Dockerfile#L120-L129

**Comment by timhaverland-noaa** [comment]
Hi Eli, the arcgis:latest image has the packages from apt.txt. I spot-tested a few of them but not sure how to test them all. If you have a better feel for testing can you give the arcgis image a look?

**Comment by eeholmes** [comment]
I only use git (directely). But the apt-txt is from the docker image used by the NASA data center teams for their workshops, so hopefully ok.

I'll close this issue.
