### ISSUE TITLE
Google Cloud Shell Idea

### ISSUE THREAD

**Issue by MichaelAkridge-NOAA** [nmfs-opensci/container-images#25]
## Google Cloud Shell Idea - Codespace Alternative
Easily use any of the container images, using docker, on google cloud via their free cloud shell/IDE
  - https://cloud.google.com/shell
### Tutorial for nmfs-opensci container images: 
  -  https://github.com/MichaelAkridge-NOAA/Open-Science-Codespaces/tree/main/google-cloud-shell
### Quick Start Link: 
[![Open in Cloud Shell](https://gstatic.com/cloudssh/images/open-btn.svg)](https://shell.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https%3A%2F%2Fgithub.com%2FMichaelAkridge-NOAA%2FOpen-Science-Codespaces&cloudshell_print=cloud-shell-readme.txt&cloudshell_workspace=google-cloud-shell&cloudshell_tutorial=TUTORIAL.md)

### Screenshot: 
![image](https://github.com/nmfs-opensci/container-images/assets/65312823/79c3af45-8aab-490c-8914-c7f36cc531c5)

**Comment by eeholmes** [comment]
@MichaelAkridge-NOAA Thanks! I added your links to the README.md.
